### ISSUE TITLE
Create a command to update hooks [feature request]

### ISSUE THREAD

**Issue by cptx032** [charignon/hooklib#2]
Would be very nice if we could to do versioning of the hooks themselfes. To do this the hook must to be inside a folder out of `.git/` folder. Maybe a config file (`.hooklib.json`) mapping the hooks events and python classes, followed by a command like `pyhooks` or `hooklib` inside project's folder can be the solution. The command could create/copy the scripts to respective hook's folders.

**Comment by charignon** [comment]
Generally, to version the hooks themselves you should keep them in a separate repository and symlink the ones you need to the `.git` directory of the repos where you want them to run. What do you think about that?

**Comment by cptx032** [comment]
This works but is not too "automagicconfigurable" :(  Anyway I can, if I want make the hooks make part of project, create a submodule inside main project. But I will need to do the manually management of hooks in .git folder by my self (creating symlinks). I can just create hooks in a dedicated folder of my project and create symlinks too. This doesnt looks to me too "magic". If I remove an hook in hooksproject the symlink would stay broken.
It seems that I talking about another project, maybe? An hooks management system? What you think about?

**update:**
exactly, I found a interesting project in github: http://git-hooks.github.io/git-hooks/
I think that this do what I'm talking about. Thanks for your time and patience :D
